### ISSUE TITLE
[Hotkey] - Tab Switch

### ISSUE THREAD

**Issue by PapaRob0** [eghernqvist/flyzer#5]
`Ctrl + Tab` like in chrome/brave would be sweet
Consequently `Ctrl + Shift + Tab` for For Previous Tab

**Comment by eghernqvist** [comment]
Ah, the fact that your things open up in tabs is a MacOS specific feature, for other OS's it opens up in separate windows. Don't think there's much control we can get over the tabs, BUT I won't say it's impossible!

**Comment by PapaRob0** [comment]
I prefer tabs so this is great. Perhaps a tab feature is on the cards? I cant be the only one right?

**Comment by eghernqvist** [comment]
> I prefer tabs so this is great. Perhaps a tab feature is on the cards? I cant be the only one right?

It's not supported on the other platforms atm sadly. To simplify the building of this project it's most likely easiest to force the MacOS version to not be tabbed either....

**Comment by eghernqvist** [comment]
Closed by #9

**Comment by eghernqvist** [comment]
Reopening until verified

**Comment by PapaRob0** [comment]
> Reopening until verified

Verified.
